name: test

on: push

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
          submodules: 'true'

    - name: Setup Fortran
      uses: awvwgk/setup-fortran@main
      id: setup-fortran
      with:
        compiler: gcc
        version: 11

    - name: Install dependencies
      run: |
        sudo apt-get install valgrind
        export OMP_NUM_THREADS=2

    - name: configure cmake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: test
      working-directory: ${{github.workspace}}/build
      run: |
        ./test/test_lsoda
        valgrind --error-exitcode=1 --leak-check=full ./test/test_lsoda
        ./test/test_threadsafe